### ISSUE TITLE
"team": required field is not set

### ISSUE THREAD

**Issue by sj26** [jradtilbrook/terraform-provider-buildkite#48]
This looks like a great update of the terraform provider!

But I noticed team support was added, and is now required. I get:

```
Error: "team": required field is not set

  on ops.tf line 14, in resource "buildkite_pipeline" "ops":
  14: resource "buildkite_pipeline" "ops" {

```

But teams is an optional feature, and not required. Is there a reason it's required by the terraform resources?

**Comment by darrylb-github** [comment]
Hey,

The new team field is required now. This is because only admins are allowed to create pipelines without teams on buildkite, so before if you were not an admin it would error out. See https://github.com/jradtilbrook/terraform-provider-buildkite/issues/31#issuecomment-637591114

Making it required prevents this and doesn't rely on the user applying being an admin.

**Comment by sj26** [comment]
> The new team field is required now.

Only if teams is enabled for the Buildkite organization. By default it is not, so requiring it here means many organizations can't use this terraform provider.

**Comment by darrylb-github** [comment]
Ah. For now I suggest locking your version to the one before and I'll push up a new PR later to make it optional and add the warning about admin access somewhere.

**Comment by jradtilbrook** [comment]
Sounds good to me. Looking forward to another contribution, thanks in advance! :+1:
